"""The agency truth table: the file-derived columns rebuild from the repository's files alone, the claims are quoted with
their path and line and each is compared with a found value, the runtime observations carry the date, command and
commit that observed them, and every verdict is one of the four the gate names."""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
TOOL = ROOT / "research" / "tools" / "agency_truth.py"
JSON = ROOT / "research" / "sources" / "agency_truth.json"
CLAIMS = ROOT / "research" / "sources" / "agency_claims.json"
OBSERVATIONS = ROOT / "research" / "sources" / "agency_truth_observations.jsonl"
DOC = ROOT / "research" / "docs" / "22_agency_truth_table.md"
VERDICTS = {"in-code-and-collected", "in-code-partial", "branch-only", "not-in-code"}
DAY = re.compile(r"^\d{4}-\d{2}-\d{2}$")

pytestmark = pytest.mark.skipif(not JSON.exists(), reason="agency_truth.json not built")


@pytest.fixture(scope="module")
def table() -> dict:
    return json.loads(JSON.read_text(encoding="utf-8"))


def test_selfcheck_holds():
    out = subprocess.run([sys.executable, str(TOOL), "--selfcheck"], capture_output=True, text=True, cwd=ROOT)
    assert out.returncode == 0 and "agency_truth selfcheck ok" in out.stdout, out.stdout[-500:] + out.stderr[-500:]


def test_the_table_rebuilds_from_the_files_alone():
    out = subprocess.run([sys.executable, str(TOOL), "build", "--check"], capture_output=True, text=True, cwd=ROOT)
    assert out.returncode == 0, out.stdout[-500:] + out.stderr[-500:]


def test_every_agency_has_a_verdict_with_a_reason_and_a_brief_ready_answer(table):
    assert table["agencies"], "no agency in the table"
    for key, row in table["agencies"].items():
        assert row["verdict"] in VERDICTS, (key, row["verdict"])
        assert row["reason"] and row["brief_ready_reason"], key
        assert isinstance(row["brief_ready"], bool)
        # the gate: only an in-code agency may take source rows, promotions or a brief
        if not row["verdict"].startswith("in-code"):
            assert row["brief_ready"] is False, key
        files = row["files"]
        assert set(files) >= {"layer_folder_exists", "registry_rows", "sources_with_documents", "sources_without_documents",
                              "event_files", "corpus", "memory_nodes", "newest_document_by_family", "coverage_cells"}, key
        assert not set(files["sources_with_documents"]) & set(files["sources_without_documents"]), key
    assert "in-code" in table["gate"]


def test_claims_are_quoted_with_path_and_line_and_compared(table):
    claims = json.loads(CLAIMS.read_text(encoding="utf-8"))["claims"]
    assert claims and len(claims) == len(table["claims"])
    for c in table["claims"]:
        assert c["quote"] and c["path"] and isinstance(c["line"], int) and c["line"] > 0, c
        assert c["verdict"] in ("matches", "mismatch", "agency not in the table"), c
        assert "found" in c, c
        path = Path(c["path"]) if c["path"].startswith("/") else ROOT / c["path"]
        if path.exists():  # the quoted sentence is on the line named, as of the commit the table records
            lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
            window = " ".join(lines[max(0, c["line"] - 2): c["line"] + 1])
            assert c["quote"][:40] in window, (c["path"], c["line"], c["quote"][:40])


def test_observations_are_dated_and_name_their_command_and_commit(table):
    rows = [json.loads(l) for l in OBSERVATIONS.read_text(encoding="utf-8").splitlines() if l.strip()] if OBSERVATIONS.exists() else []
    assert rows == table["observations"]
    for o in rows:
        assert DAY.match(o["date"]) and o["command"] and o["result"] and o["kind"] in ("db_built", "stage_ran", "stage_failed", "tests", "collect_ran"), o
        assert re.fullmatch(r"[0-9a-f]{7,40}", o["commit"] or ""), o


def test_the_document_is_generated_and_states_the_gate():
    text = DOC.read_text(encoding="utf-8")
    assert "Generated by `research/tools/agency_truth.py build`" in text
    assert "## Verdict per agency" in text and "## Runtime observations" in text and "## Claimed versus found" in text
    assert "only for agencies whose verdict starts with in-code" in text
