#!/usr/bin/env python3
"""Check a loaded copy against the load plan, and the plan's rows against their saved sources.

    python research/tools/load_verify.py readback DIR [--db EXPORT]        # write DIR/readback.sql
    python research/tools/load_verify.py copy (--from DIR | --loaded DB) --snapshot SNAP --offices FILE [--db EXPORT]
    python research/tools/load_verify.py sources --snapshot SNAP --offices FILE [--db EXPORT]
    python research/tools/load_verify.py --selfcheck

The rows checked are the ones promote_plan.build makes the load file from, so a row production
refuses, already states or holds for a decision is not expected in the copy.

readback writes one psql script for the read-only check login on the hosted copy: every table the
load writes, one JSON row per line, read exactly as the export is read, plus row counts. Run it
from DIR with the password typed at the prompt, after each load run; the second run's counts.txt
must equal the first's.

copy compares every planned row with the copy by primary key and every carried column.

sources reads each planned row that a report rests on back to the saved file it came from:
requirements (one need per source key, the forecast rows a title hash once merged), offices
(what each match rests on, and that each created office has a source and a parent the load
knows) and dated role claims (a notice contact's date and name against the saved notice, a
leadership date against the organization memory that states it, and a person a saved page names
against that page and the date it writes).
"""

from __future__ import annotations

import argparse
import csv
import functools
import hashlib
import html
import json
import re
import sys
from collections import Counter
from datetime import date
from pathlib import Path
from urllib.parse import unquote

import openpyxl

import promote_plan as pp
from agency import MANIFEST, MEMORY, SAM_NOTICES
from fetch import kept_page
from reader import pdf_text

ROOT = Path(__file__).resolve().parents[2]
SEED = MEMORY / "organization_seed.json"


def readback_sql(carried: dict, numeric: dict, pk: dict) -> str:
    tables = [*pp.TABLES, *pp.TRIGGER_FILLED, "gov_need_lifecycle_history"]
    lines = ["-- Read back what the Navy load wrote, generated by research/tools/load_verify.py.",
             "-- Run from this directory with the read-only check login on the copy:",
             "--   psql 'postgresql://chromie_navy_check.<project ref>@<session pooler host>:5432/postgres' -f readback.sql",
             "\\set ON_ERROR_STOP on", "\\set FETCH_COUNT 5000", "set default_transaction_read_only = on;",
             "\\pset footer off", "\\o counts.txt",
             " union all\n".join(f"select '{t}' as table_name, count(*) from public.\"{t}\"" for t in tables)
             + " order by 1;", "\\t on", "\\a"]
    for table in pp.TABLES:
        lines += [f"\\o {table}.jsonl", pp.rows_sql(table, carried[table], numeric.get(table, set()), pk[table]) + ";"]
    return "\n".join(lines + ["\\o", ""])


def compare(final: dict, loaded: dict, carried: dict, pk: dict) -> int:
    """Missing rows and differing cells per table; the copy's other rows are production's own."""
    bad = 0
    for table in pp.TABLES:
        theirs = {tuple(r[c] for c in pk[table]): r for r in loaded[table]}
        missing = differ = 0
        example = ""
        for row in final[table]:
            got = theirs.get(tuple(row[c] for c in pk[table]))
            if got is None:
                missing += 1
                continue
            for column in carried[table]:
                if got.get(column) != row[column]:
                    differ += 1
                    example = example or f"  e.g. {column} of {tuple(row[c] for c in pk[table])}"
        bad += missing + differ
        print(f"{table:<34} {len(final[table]):>7} planned  missing {missing:>5}  differing cells {differ:>5}{example}")
    print("every planned row is in the copy with every column equal" if not bad else f"{bad} problems")
    return bad


# ----------------------------------------------------------------- sources

LIST = 12
FORECAST_EXCERPT = re.compile(r"^(?P<release>\S+) (?P<sheet>.+)!row (?P<row>\d+), source sha256 (?P<sha>[0-9a-f]{64})$")
# June 2024 NAVWAR rows that read alike (PMA/PMW-101, "Order to Contract #N0003922D4001") and were once one record.
LOST = ("lrae_navwar_2024-06", (406, 408, 409, 410, 411))


def norm(text) -> str:
    return " ".join(html.unescape(str(text or "")).split()).casefold()


def tally(title: str, counts: Counter, listed: list[str]) -> int:
    """Print one check's counts and its first listed rows; a count named mismatch fails the run."""
    print(f"\n{title}")
    for what, n in sorted(counts.items()):
        print(f"  {n:>7,}  {what}")
    for line in listed[:LIST]:
        print(f"    {line}")
    if len(listed) > LIST:
        print(f"    ... and {len(listed) - LIST} more")
    return sum(n for what, n in counts.items() if "mismatch" in what)


@functools.cache
def file_sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


@functools.cache
def sheet_text(path: Path, sheet: str) -> dict[int, str]:
    """Each spreadsheet row's cells as one normalized string, by the row number Excel shows."""
    book = openpyxl.load_workbook(path.open("rb"), data_only=True)  # a saved file may carry no .xlsx name
    rows = book[sheet].iter_rows(min_row=1, values_only=True)
    return {n: norm(" ".join(str(v) for v in row if v is not None)) for n, row in enumerate(rows, start=1)}


@functools.cache
def notice(notice_id: str) -> dict | None:
    path = SAM_NOTICES / f"{notice_id}.json"
    if not path.exists():
        return None
    raw = json.loads(path.read_text(encoding="utf-8", errors="replace"))
    body = raw.get("data2") or raw.get("data") or raw
    return {"posted": str(raw.get("postedDate") or body.get("postedDate") or "")[:10], "title": body.get("title") or "",
            "contacts": norm(json.dumps(body.get("pointOfContact") or []))}


def requirement_check(ev: dict, statement: str) -> str:
    """Read one requirement revision's evidence back to the saved file it names."""
    if ev["provider"] == "sam.gov":
        saved = notice(ev["source_key"].split(":", 1)[1])
        if saved is None:
            return "notice not saved"
        if saved["posted"] != str(ev["published_at"])[:10]:
            return "mismatch: posted date differs from the saved notice"
        return "confirmed against the saved notice" if norm(saved["title"]) in norm(statement) else \
            "mismatch: title differs from the saved notice"
    if m := FORECAST_EXCERPT.match(ev["excerpt"] or ""):
        source = json.loads((ROOT / "datapack" / m["release"] / "SOURCE.json").read_text())
        raw = ROOT / source["raw_path"]
        if not raw.exists():
            return "forecast file not saved"
        if file_sha(raw) != m["sha"]:
            return "mismatch: forecast file bytes differ from the stated sha256"
        cells = sheet_text(raw, m["sheet"]).get(int(m["row"]), "")
        return "confirmed against the forecast row" if norm(statement) in cells else \
            "mismatch: the forecast row does not carry the statement"
    return f"other evidence ({ev['provider']})"


def requirements(final: dict) -> int:
    needs = {n["id"]: n for n in final["gov_needs"]}
    need_of = {r["id"]: r["need_id"] for r in final["gov_need_requirements"]}
    evidence = {e["id"]: e for e in final["gov_intelligence_evidence"]}
    cites: dict[str, list[dict]] = {}
    for link in final["gov_assertion_evidence"]:
        if link["evidence_id"] in evidence:
            cites.setdefault(link["assertion_id"], []).append(evidence[link["evidence_id"]])
    counts, listed, need_at = Counter(), [], {}
    for rev in final["gov_requirement_revisions"]:
        need = needs[need_of[rev["requirement_id"]]]
        for ev in cites.get(rev["assertion_id"], []) or [None]:
            verdict = requirement_check(ev, rev["statement"]) if ev else "mismatch: no loaded evidence"
            counts[verdict] += 1
            if verdict.startswith("mismatch"):
                listed.append(f"{need['source_key']}: {verdict}")
            if ev and (m := FORECAST_EXCERPT.match(ev["excerpt"] or "")):
                need_at[(m["release"], int(m["row"]))] = need["id"]
    keys = Counter((n["source"], n["source_key"]) for n in needs.values())
    counts["mismatch: (source, source_key) shared by two needs"] = sum(n > 1 for n in keys.values())
    bad = tally(f"requirements: {len(needs):,} needs, {len(keys):,} distinct (source, source_key); "
                "each revision's evidence read back to its saved file", counts, listed)

    # The rows once merged: their sheet rows from the release's own evidence layer, then the needs those rows load.
    release, row_numbers = LOST
    pack = ROOT / "datapack" / release / "layers"
    keys_wanted = {f"row:{release}:{n}" for n in row_numbers}
    evidence_of = {r["record_key"]: r["evidence_id"] for r in csv.DictReader((pack / "needs.csv").open()) if r["record_key"] in keys_wanted}
    sheet_rows = {r["id"]: int(r["locator"].rsplit(" ", 1)[1]) for r in csv.DictReader((pack / "evidence.csv").open())}
    found = {key: need_at.get((release, sheet_rows[evidence_of[key]])) for key in sorted(evidence_of)}
    distinct = {n for n in found.values() if n}
    print(f"\n{release} rows {', '.join(map(str, row_numbers))}: {len(distinct)} distinct loaded needs of {len(row_numbers)}")
    for key, need_id in found.items():
        print(f"    {key:<32} -> {need_id or 'not loaded'}  {needs[need_id]['title'][:60] if need_id else ''}")
    return bad + (len(distinct) != len(row_numbers))


def source_file(source: str) -> Path | None:
    """The repository file a provenance string names ("federal-buyer-map-trial/research/memory/x.json")."""
    rest = source.split("/", 1)[1] if "/" in source else source
    return ROOT / rest if (ROOT / rest).is_file() else None


@functools.cache
def file_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def offices(built: dict) -> int:
    local = {r["id"]: r for r in built["export"]["gov_organizations"]}
    counts, listed = Counter(), []
    for local_id, (p, how) in sorted(built["matched"].items(), key=lambda m: local[m[0]]["source_ref"]):
        row = local[local_id]
        ok = {"office code": lambda: pp.office_codes(row) & pp.office_codes(p),
              "exact name": lambda: pp.office_names(row) & pp.office_names(p),
              "agency": lambda: built["agency_map"].get(row["existing_agency_id"]) == p.get("existing_agency_id"),
              "decision": lambda: built["reasons"].get(row["source_ref"])}[how]()
        counts[f"reused, by {how}: {'confirmed' if ok else 'mismatch'}"] += 1
        if how == "decision" or not ok:
            listed.append(f"{row['source_ref']:<24} {row['name'][:34]:<34} -> {p['name'][:40]}"
                          + (f"; {built['reasons'].get(row['source_ref'], 'no reason written')}" if how == "decision" else ""))
    created = built["final"]["gov_organizations"]
    known = {p["id"] for p in built["prod"]["gov_organizations"]} | {r["id"] for r in created}
    for row in created:
        path = source_file(row["source"] or "")
        stated = bool(path and row["source_ref"] and row["source_ref"] in file_text(path))
        parent = row["parent_organization_id"] is None or row["parent_organization_id"] in known
        counts[f"created: {'source confirmed' if stated else 'mismatch: source does not state it'}"] += 1
        if not parent:
            counts["mismatch: created under a parent the load does not know"] += 1
        if row["parent_organization_id"] is None:
            counts["created with no parent"] += 1
        if not (stated and parent):
            listed.append(f"{row['source_ref']:<24} {row['name'][:40]} ({row['source']}, parent {row['parent_organization_id']})")
    return tally(f"offices: {len(built['matched'])} reused, {len(created)} created", counts, listed)


# Words around a name that are not the name: ranks, honorifics and suffixes.
NOT_NAME = frozenset("adm vadm radm rdml capt cdr lcdr lt ltjg ens cwo col ltc maj cpt gen ltg mg bg sgt msgt "
                     "dr mr mrs ms hon honorable jr sr ii iii iv".split())


def states_date(day: str, text: str) -> bool:
    """The text writes the date as pages and file names do: 2026-04-22, April 22, 2026, 22 Apr 2026, 4/22/2026,
    20260422 or 04222026."""
    try:
        d = date.fromisoformat(day)
    except ValueError:
        return False
    month = d.strftime("%B")[:3].casefold()
    forms = (day, f"{d:%Y%m%d}", f"{d:%m%d%Y}", f"{d.month}/{d.day}/{d.year}", f"{d:%m/%d/%Y}")
    return any(f in text for f in forms) or bool(
        re.search(rf"\b{month}[a-z]*\.? {d.day},? {d.year}\b|\b{d.day} {month}[a-z]*\.?,? {d.year}\b", text))


def names_person(name: str, email: str, text: str) -> bool:
    """The text names the person: their e-mail, or their first and last name as words (a middle name may be left out,
    and a first name of three letters or more may stand for the longer one it begins, as Kim for Kimberly)."""
    words = [w for w in re.findall(r"[a-z]{2,}", norm(name)) if w not in NOT_NAME]
    if email and norm(email) in text:
        return True
    first = re.escape(words[0]) + ("[a-z]*" if len(words[0]) >= 3 else "") if words else ""
    if len(words) > 1 and words[0] + words[-1] in text:
        return True  # PDF text can run a name together: "ericandalis"
    return bool(words) and all(re.search(rf"\b{w}\b", text) for w in (first, re.escape(words[-1])))


def roles(built: dict) -> int:
    final, prod, export = built["final"], built["prod"], built["export"]
    contacts = {c["id"]: c for c in export["gov_contacts"]} | {c["id"]: c for c in prod["gov_contacts"]}
    seed = json.loads(SEED.read_text())
    leads = {r["id"]: r for r in seed["relationships"]}
    observed = {o["id"]: o for o in seed["observations"]}
    counts, listed = Counter(), []
    for pos in final["gov_contact_positions"]:
        person = contacts.get(pos["contact_id"], {})
        name, email, day = person.get("name") or "", person.get("email") or "", str(pos["observed_at"])[:10]
        if pos["source"] == "sam_gov_site_api":
            saved = notice(pos["source_ref"])
            verdict = ("notice contact: notice not saved" if saved is None else
                       "notice contact: mismatch, date differs from the saved notice" if saved["posted"] != day else
                       "notice contact: date and person confirmed against the saved notice"
                       if names_person(name, email, saved["contacts"]) else
                       "notice contact: mismatch, the saved notice does not name the person")
        elif pos["source"].endswith(SEED.name):
            rel = leads.get(pos["source_ref"])
            cited = [observed[o] for o in (rel or {}).get("observation_ids", []) if o in observed]
            if rel is None:
                verdict = "leadership: mismatch, the organization memory lacks the claim"
            elif (rel.get("effective_from"), rel.get("effective_to")) != (pos["valid_from"], pos["valid_to"]):
                verdict = "leadership: mismatch, dates differ from the organization memory"
            elif day != max(o["observed_at"] for o in cited):
                verdict = "leadership: mismatch, observed date is not the newest observation's"
            elif pos["valid_from"] or pos["valid_to"]:
                verdict = f"leadership with dates: as the organization memory states them ({rel.get('effective_dates_status')})"
                listed.append(f"{name}: {pos['raw_title'][:60]}, from {pos['valid_from'] or 'unstated'} to "
                              f"{pos['valid_to'] or 'now'}; {rel.get('effective_dates_note') or ''} "
                              f"[{', '.join(o['source_url'] for o in cited)}]")
            else:
                verdict = "leadership without dates: observed date confirmed against the organization memory"
        else:
            path = cited_copies().get(pos["source_ref"]) or saved_page(pos["source_url"])
            text = page_text(path) if path else ""
            verdict = ("dated observation: page not saved" if path is None else
                       "dated observation: mismatch, the saved page does not name the person"
                       if not names_person(name, email, text) else
                       "dated observation: date and person confirmed on the saved page or its address"
                       if states_date(day, text + " " + norm(unquote(pos["source_url"]))) else
                       "dated observation: person confirmed, the date is not written on the page in a form read here")
            if verdict.endswith("read here"):
                listed.append(f"{pos['source']} {pos['source_url']}: {name}: {day}")
        counts[verdict] += 1
        if "mismatch" in verdict:
            listed.append(f"{pos['source']} {pos['source_ref']}: {name}: {verdict}")
    return tally(f"dated role claims: {len(final['gov_contact_positions']):,} positions", counts, listed)


@functools.cache
def saved_pages() -> dict[str, Path]:
    """Saved files by every URL they answer to: the newest kept copy in the document ledger, as the builders read it
    (an earlier fetch may have landed on an error page), then each forecast release's own record."""
    pages = {}
    for line in MANIFEST.open(encoding="utf-8"):
        rec = json.loads(line)
        for url in (rec.get("url"), rec.get("fetched_from"), rec.get("final_url")):
            if url and kept_page(rec):
                pages[page_key(url)] = ROOT / rec["path"]
    for source in (ROOT / "datapack").glob("*/SOURCE.json"):
        rec = json.loads(source.read_text())
        for url in (rec.get("source_url"), rec.get("fetched_from")):
            if url and rec.get("raw_path"):
                pages.setdefault(page_key(url), ROOT / rec["raw_path"])
    return pages


@functools.cache
def cited_copies() -> dict[str, Path]:
    """The saved copy each contact observation names by its hash; a later fetch of the same address may have been
    redirected elsewhere."""
    copies = {}
    for row in json.loads((MEMORY / "contact_observations.json").read_text(encoding="utf-8")):
        found = re.search(r"sha256 ([0-9a-f]{12,64})", row.get("source_revision") or "")
        files = sorted((ROOT / "data" / "raw").glob(f"{found[1][:12]}_*")) if found else []
        match = [f for f in files if file_sha(f).startswith(found[1])]
        if match:
            copies[row["id"]] = match[0]
    return copies


def page_key(url: str) -> str:
    """A saved page answers to its address without the scheme: the ledger kept some hearing pages under http."""
    return unquote(url).split("://", 1)[-1]


def saved_page(url: str | None) -> Path | None:
    path = saved_pages().get(page_key(url or ""))
    return path if path and path.is_file() else None


@functools.cache
def page_text(path: Path) -> str:
    """A saved page as normalized text: a PDF through pdftotext, a workbook's cells, anything else with tags removed."""
    head = path.read_bytes()[:4]
    if head == b"%PDF":
        return norm(pdf_text(path))
    if head.startswith(b"PK"):
        try:
            book = openpyxl.load_workbook(path.open("rb"), data_only=True, read_only=True)
            return norm(" ".join(str(v) for sheet in book.worksheets for row in sheet.iter_rows(values_only=True)
                                 for v in row if v is not None))
        except Exception:  # noqa: BLE001 - a zip that is not a workbook is read as text below
            pass
    return norm(re.sub(r"<[^>]+>", " ", file_text(path)))


def trace(built: dict) -> int:
    bad = requirements(built["final"]) + offices(built) + roles(built)
    print("\nevery traced row agrees with its saved source" if not bad else f"\n{bad} mismatches")
    return 1 if bad else 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("what", choices=("readback", "copy", "sources"))
    parser.add_argument("dir", nargs="?", type=Path)
    parser.add_argument("--db", default="navy_proof_ac", help="local database holding the export")
    parser.add_argument("--snapshot", type=Path, help="the production snapshot the load file was made from")
    parser.add_argument("--offices", type=Path, help="the office decisions the load file was made with")
    parser.add_argument("--from", dest="source_dir", type=Path, help="a readback directory")
    parser.add_argument("--loaded", help="a local database the file was loaded into")
    args = parser.parse_args(argv)

    if args.what == "readback":
        if not args.dir:
            parser.error("readback needs DIR")
        columns, numeric, pk, _ = pp.catalog(pp.LOCAL + args.db)
        carried = {t: [c for c in columns[t] if c not in pp.PRODUCTION_FILLS] for t in pp.TABLES}
        args.dir.mkdir(parents=True, exist_ok=True)
        (args.dir / "readback.sql").write_text(readback_sql(carried, numeric, pk))
        print(f"wrote {args.dir / 'readback.sql'}; run it there with psql and the check login")
        return 0
    if not (args.snapshot and args.offices):
        parser.error("copy and sources need --snapshot and --offices, as the load file was made")
    built = pp.build(args.db, args.snapshot, json.loads(args.offices.read_text()))
    final, carried, numeric, pk = built["final"], built["carried"], built["numeric"], built["pk"]
    if args.what == "copy":
        if bool(args.source_dir) == bool(args.loaded):
            parser.error("copy needs one of --from DIR or --loaded DB")
        if args.loaded:
            loaded = {t: pp.export_rows(pp.LOCAL + args.loaded, t, carried[t], numeric.get(t, set()), pk[t])
                      for t in pp.TABLES}
        else:
            loaded = {t: [json.loads(line) for line in (args.source_dir / f"{t}.jsonl").read_text().splitlines()]
                      for t in pp.TABLES}
        return 1 if compare(final, loaded, carried, pk) else 0
    return trace(built)


def selfcheck() -> int:
    final = {t: [] for t in pp.TABLES}
    final["gov_needs"] = [{"id": "n1", "title": "a"}, {"id": "n2", "title": "b"}]
    pk = {t: ("id",) for t in pp.TABLES}
    carried = {t: ["id", "title"] for t in pp.TABLES}
    loaded = {t: [] for t in pp.TABLES}
    loaded["gov_needs"] = [{"id": "n1", "title": "a"}, {"id": "n2", "title": "B"}, {"id": "p9", "title": "theirs"}]
    assert compare(final, loaded, carried, pk) == 1, "one differing cell; production's own row is not a problem"
    loaded["gov_needs"] = loaded["gov_needs"][:1]
    assert compare(final, loaded, carried, pk) == 1, "one missing row"
    script = readback_sql(carried, {"gov_needs": {"title"}}, pk)
    assert "set default_transaction_read_only = on;" in script and "\\o gov_needs.jsonl" in script
    assert '"title"::text as "title"' in script and "\\o counts.txt" in script
    # A rank, a middle name or a nickname with the same e-mail is the same person; a surname inside a word is not.
    poc = norm('[{"fullname": "jonathan pagnucco", "email": "jonathan.p.pagnucco.mil@us.navy.mil"}]')
    assert names_person("CDR Jonathan Pagnucco", "", poc)
    assert names_person("Mary Helen Dent", "", norm("mary dent"))
    assert names_person("MARCIE WAGERS", "marcia.m.wagers.civ@us.navy.mil", norm("marcia wagers marcia.m.wagers.civ@us.navy.mil"))
    assert not names_person("Mary Dent", "", norm("mary student"))
    assert names_person("Kim Martin", "kim.martin@nrl.navy.mil", norm("kimberly martin"))
    assert not names_person("Kim Martin", "", norm("kimberly martinez"))
    assert names_person("Eric Andalis", "", "capt raphael castillejo ericandalis program manager")
    assert not names_person("CDR", "", poc)
    assert states_date("2026-04-22", norm("Hearing, April 22, 2026")) and states_date("2026-04-22", "22 apr. 2026")
    assert states_date("2025-01-31", norm(unquote("2025_PMW%20160_Tear%20Sheet_v01312025.pdf")))
    assert not states_date("2026-04-22", "april 2, 2026") and not states_date("", "x")
    assert page_key("https://docs.house.gov/a%20b") == page_key("http://docs.house.gov/a b")
    print("selfcheck ok")
    return 0


if __name__ == "__main__":
    sys.exit(selfcheck() if sys.argv[1:] == ["--selfcheck"] else main(sys.argv[1:]))
